# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-29 10:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=200)),
                ('longitude', models.FloatField(default=0)),
                ('latitude', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='soil_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='date published')),
                ('moisture', models.FloatField(default=0)),
                ('plant_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plants.plant')),
            ],
        ),
        migrations.CreateModel(
            name='tank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(default=0)),
                ('latitude', models.FloatField(default=0)),
                ('tank_volume', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='tank_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='date published')),
                ('water_level', models.FloatField(default=0)),
                ('tank_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plants.tank')),
            ],
        ),
        migrations.CreateModel(
            name='ws',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(default=0)),
                ('latitude', models.FloatField(default=0)),
                ('location_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ws_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField(default=0)),
                ('humidity', models.FloatField(default=0)),
                ('rainfall', models.FloatField(default=0)),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='date published')),
                ('ws_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plants.ws')),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='tank_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plants.tank'),
        ),
        migrations.AddField(
            model_name='plant',
            name='ws_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plants.ws'),
        ),
    ]
