# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 08:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soil',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='water_reservoir',
            name='reservoir_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weather_station',
            name='station_no',
            field=models.IntegerField(default=0),
        ),
    ]
