# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 13:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plants', '0002_auto_20171006_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='water_reservoir',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='weather_station',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='date published'),
        ),
    ]
