# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plants', '0003_auto_20171006_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='water_reservoir',
            name='plant_key',
        ),
        migrations.RemoveField(
            model_name='weather_station',
            name='plant_key',
        ),
        migrations.AddField(
            model_name='soil',
            name='humidity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='soil',
            name='rainfall',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='soil',
            name='temp',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='soil',
            name='water_level',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='water_reservoir',
        ),
        migrations.DeleteModel(
            name='weather_station',
        ),
    ]
